apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis-http-session
  name: redis-http-session
  namespace: redis-http-session
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis-http-session
  template:
    metadata:
      labels:
        app: redis-http-session
    spec:
      containers:
      - image: ghcr.io/mochizuki875/redis-http-session:redis7.0.5 
        name: redis-http-session
        # imagePullPolicy: Always
        resources:
          limits:
            memory: "1Gi"
            cpu: "1"
        env:
        - name: SESSION_STORE
          value: redis
        - name: REDIS_HOST
          value: redis.redis-http-session.svc
        - name: REDIS_PORT
          value: "6379"

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-http-session
  name: redis-http-session
  namespace: redis-http-session
spec:
  type: LoadBalancer
  selector:
    app: redis-http-session
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redis-http-session-ingress
  namespace: redis-http-session
spec:
  ingressClassName: nginx
  rules:
  - host: redis-http-session.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: redis-http-session
            port:
              number: 8080